---
version: "1.0"
nodes:
  - name: Device
    namespace: Kube
    display_labels: ["name__value"]
    inherit_from:
      - CoreArtifactTarget
    attributes:
      - name: name
        kind: Text
        label: Name
        optional: false
        unique: true
      - name: description
        kind: Text
        label: Description
        optional: true