query ($name: String) {
  AvdLeafswitch(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        primary_address {
          node {
            address {
              value
            }
          }
        }
      }
    }
  }
}