query ($id: [ID]) {
  AvdLeafswitch(ids: $id) {
    edges {
      node {
        id
        primary_address {
          node {
            address {
              value
            }
          }
        }
      }
    }
  }
}
